name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0' # Or your version

dependencies:
  flutter:
    sdk: flutter

  # Your other packages will be listed here
  cupertino_icons: ^1.0.8
  supabase_flutter: any
  logger: ^2.5.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.1.2
  mime: ^1.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true