name: myapp
description: "AL-Tijwal Agent - Location-Based Task Management"
publish_to: 'none'

version: 1.2.1+4

environment:
  sdk: '>=2.19.0 <3.0.0' # Or your version

dependencies:
  flutter:
    sdk: flutter

  # Your existing packages
  cupertino_icons: ^1.0.8
  supabase: any
  supabase_flutter: any
  logger: ^2.5.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  mime: ^1.0.5
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3
  uuid: ^4.5.1
  table_calendar: ^3.0.9
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.5
  url_launcher: ^6.2.3
  device_info_plus: ^10.1.0
  http: ^1.1.0
  signature: ^5.5.0
  share_plus: ^10.1.2
  google_fonts: ^6.1.0
  package_info_plus: ^8.0.0
  open_file: ^3.3.2
  timezone: ^0.9.4
  # ----------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - icons/logo1.png
    - icons/logo2.png
    - icons/logo2_padded.png
    - icons/logo3.png
    - assets/images/logo1.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/whatsapp.png
  

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: false
  web:
    generate: true
    image_path: "icons/logo2_padded.png"
    background_color: "#2563EB"
    theme_color: "#2563EB"
  image_path: "icons/logo2_padded.png"
  adaptive_icon_background: "#2563EB"
  adaptive_icon_foreground: "icons/logo2_padded.png"
  min_sdk_android: 21
