name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0' # Or your version

dependencies:
  flutter:
    sdk: flutter

  # Your existing packages
  cupertino_icons: ^1.0.8
  supabase: any
  supabase_flutter: any
  logger: ^2.5.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  mime: ^1.0.5
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3
  uuid: ^4.5.1
  table_calendar: ^3.0.9
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.4
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.5
  url_launcher: ^6.2.3
  device_info_plus: ^10.1.0
  http: ^1.1.0
  signature: ^5.5.0
  share_plus: ^10.1.2
  # ----------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
