name: Supabase Backup to Google Drive

on:
  schedule:
    # Daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

env:
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
  GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}

jobs:
  backup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Run database backup
        run: .github/scripts/backup-database-api.sh

      - name: Upload database backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-backup
          path: database-backup-*.tar.gz
          retention-days: 1

  backup-storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Run storage backup
        run: .github/scripts/backup-storage.sh

      - name: Upload storage backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: storage-backup
          path: storage-backup-*.tar.gz
          retention-days: 1

  upload-to-drive:
    needs: [backup-database, backup-storage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2
          pip install google-api-python-client

      - name: Download database backup
        uses: actions/download-artifact@v4
        with:
          name: database-backup

      - name: Download storage backup
        uses: actions/download-artifact@v4
        with:
          name: storage-backup

      - name: Upload to Google Drive
        run: python .github/scripts/upload-to-drive.py

      - name: Cleanup old backups
        run: python .github/scripts/cleanup-old-backups.py

  notify:
    needs: upload-to-drive
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send notification
        run: |
          if [ "${{ needs.upload-to-drive.result }}" == "success" ]; then
            echo "✅ Backup completed successfully"
          else
            echo "❌ Backup failed - check logs"
          fi